# Child / Parent configurations are considered when this file is the "main" SwiftLint configuration file
# This setup is used for the target specific build phase scripts
parent_config: ../.swiftlint.yml

opt_in_rules:
# - missing_docs
